name: cvd_simulator
description: Simulate how your app looks to people with color vision deficiency.
version: 1.0.0
repository: https://github.com/fischerscode/flutter-cvd_simulator

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
